# Fusion Backtest - Only generate (no training)
input_dim: 3843
hidden_dim: 512
output_dim: 256
dropout: 0.2

save_path: E:/TDTu/TAI_LIEU/KY1-NAM5/DU_AN_CNTT/results/fusion_rl/train_inference/fusion_checkpoint.pt

sources:
  transformer_embeddings: E:/TDTu/TAI_LIEU/KY1-NAM5/DU_AN_CNTT/results/backtest/lstm_advanced/transformer_backtest_embeddings.npy
  attcnn_embeddings: E:/TDTu/TAI_LIEU/KY1-NAM5/DU_AN_CNTT/results/backtest/lstm_advanced/att_cnn_backtest_embeddings.npy
  finbert_embeddings: E:/TDTu/TAI_LIEU/KY1-NAM5/DU_AN_CNTT/results/backtest/finbert/finbert_daily_embeddings_backtest.npy
